### ISSUE TITLE
[BUG] Crash after leaving the vampire village on campaign map.

### ISSUE THREAD

**Issue by AJIexander** [TheOldRealms/TOW_Core#251] opened 2022-05-20 16:37 UTC
**Describe the bug**
I went to take a quest to destroy bandits in a vampire village. After the download was completed, when leaving the village, a crash occurred on the map of the company.
**To Reproduce**
 1. Accept quest to destroy bandits in a vampire village
 2. Complete the quest
 3. Leave the village
 4. Crash

**Expected behavior**

**Screenshots**

**Additional context**

[rgl_log_errors_13344.txt](https://github.com/TheOldRealms/TOW_Core/files/8742080/rgl_log_errors_13344.txt)
[rgl_log_13344.txt](https://github.com/TheOldRealms/TOW_Core/files/8742081/rgl_log_13344.txt)

**Comment by Jasonleh99** [comment] 2022-05-20 17:35
Looking at your logs, it looks like you're missing some Terrain Shaders, please delete your shaders in your bannerlords folder in C:/ProgramData/

Then verify integrity of your game files.

**Comment by Jasonleh99** [comment] 2022-05-21 16:48
Not reproducible on our end, closing now

Reach out to us on discord and we can help you personally

**Closed as completed by Jasonleh99** 2022-05-21 16:48 UTC
Labels: bug, 3
