### ISSUE TITLE
[BUG] Crash after the end of the battle with the bandits (Outlaw Party) when loading the game on the campaign map №2.

### ISSUE THREAD

**Issue by AJIexander** [TheOldRealms/TOW_Core#254] opened 2022-05-20 16:54 UTC
**Describe the bug**
Crash after the end of the battle with the bandits when loading the game on the campaign map.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
[rgl_log_errors_5372.txt](https://github.com/TheOldRealms/TOW_Core/files/8742090/rgl_log_errors_5372.txt)
[rgl_log_5372.txt](https://github.com/TheOldRealms/TOW_Core/files/8742091/rgl_log_5372.txt)

**Comment by Jasonleh99** [comment] 2022-05-20 17:38
Duplicate of https://github.com/TheOldRealms/TOW_Core/issues/253

**Closed as completed by Jasonleh99** 2022-05-20 17:38 UTC
Labels: bug, 3
